language: javascript
node_js:
  - '12'
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
tags: true
#попробовать убрать коменты
install:
#  - npm install –g angular-cli
script:
  - ng set --global warnings.packageDeprecation=false
addons:
  ssh_known_hosts: 142.93.130.144
before_deploy:
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/authorized_keys
  - ng build --prod
#  - gem install mime-types -v 2.6.
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/authorized_keys
  - ssh-add $TRAVIS_BUILD_DIR/authorized_keys
  - bundle exec rake publish
env:
  global:
    - REMOTEAPPDIR=/var/deployAng/
    - REMOTEUSER=root
    - REMOTEHOST=142.93.130.144
    - secure: ItG/X1Ex8D5b5MhSbt6CIJhKrVYbfMNcgsRxnIP2KNS9dD3ArESo9usjh8mLLdYNWRRA7I9fyE2k3VgaY7AJmjKE6ZkP8olQm/dgljXuMEHlQdZsOqt59tEKma+eYV2FdIKoWHJ426v71sFbUYeumUJOoDthnTm9Z1g+YvpLV6ewbR2fq1YiuZKbTnF33QT/pqyc3vfNDpUdhRkrNIyC2hfC1qQnnQTd60wj64SKEpkjxuafCh7Cya55OklubZk/5y4ohbQLdnsWRIEBBGNCZfNpBQXHlXHGuw8mxhRwxjdiPD0jEEJ57pLeMWiWlU3+fDs2wfvZDs58gjcZqGLPfuIW243kKXX/Ymb03HHTRGWI9pndcsuK0Xz8sAPP8eXZw5MWMwNRmZENTiXAjR9WL41hOJiV1TjpCe1XFeMn77IYm+oTFMRvtIF9t7V3V47B97IeAizZFJOnPUGVQa7LG9MXMv8ScIfWMiOxw6CeamCAhVqhiFS7Fi6HWGjigf1mj2dUqHQySJdrZv91fEEMLCo2kXb+OtbAZJAKUuaMqm/+jZv1CYac4cUgYA6nH0mg6hxtjsJ6BcxdYFo6G+BOS3xGqjH8aakhEsxOZj7WLR5lR83pXhy+NqDzsO2sIVpvyXq3a+4mYCmJs9aj6PKkvAS4x3PKhmzZCcsUBr8adRg=
    - secure: mjLcDrb6MbZWX1MPUcW2tLNbKi+OR/goSYqA5Z6h74kft/2ltge905DHdA+mnt1AH/mxferSMnFlM2aDcB3LRtG5HE61ou/YO07avSAZP9E8sZl+dDBp7yNdi69Yp9EYnm3GNaZInhSM3/MyOHmQaNHKDBJ45wdi0zgg/xo5LjHs2QybdBCzcbFnT53aYWhQZ8f04mqAX5FOlJrtnTNfufq12RBrssqgyi6h6mWbHNsupkjxX+yYwM6SFxApfDLSYp95+hCMRNq6zUPnvadXbuNBiN4wMuDSYjvVtQr1z6g0KEZ6ow1zYIspyNVniz/gpZ/fHnxRB2nDyAwCNX2GtdJDOom6bkcegf5uyqAgOLlDpjN1LXQpnjkDX4Zrx9C4KEA45Io/jjPFtRDaTIPNrLZoTCCGyVzR7XUM5iBDVU8FDxzjfUwMdfkFq7Q+UKq0pBF3HK/Y+M7W39oqXkSeiz9Blm0EaAhbxtT3HtJ2WsQkztgdKK4AQmXmr2TDL/SwVzOMDF6hF7MSFwOm2Axao12uybIAjkCWlXLxE776kpOCc2LvIHQSO7QKb40FMYhFriFhbZI8cu/QuqJGkRB53DmHTGMiWNElMqRaxl9P58fv44Ku9DolXBUCo23r5WtdQ9U2M/2gY+IOCEtFsyQi+uFXRh+/roxlTofL3BjyUyo=
    - secure: N6LsImovWSb7MqUX6XGUl5OuClIcCio6JbalD3apRxTj2eN48ioA9h42ks7q9lNnjSqhIUzUw8ZwzxTBgYVQstWzJALn0Z4w5CamTE/dP6zp7uRmrw1L7kO88frDAfJU8ywDDbB4DvPx5Q4l/5esQJYkVR5cPSQE2VMMZPck/UrrebZvwRDNoDS0VZZkX12zrWLqUCcybwxVgW+cxSM/aYj4t/unSuSr2qi81ZMVs1eNYKB6wmbrCsh1hpxoDrysDFMUS5hd87ZxIGIGSZXUQ49rCoiBXVVL2Fcl3Aha/xP5w2Ere27RWGO7O9D0+wgSYFKvtqKbvbMMWyMNf73sgT1ovSFPHK0K37ANPC74p5iuhDTcIRcR7e3gYOrzfg7v55TqtKrfSY4g/oyE+7BRg4hwNnaY5VWervk46FWa+PAViusA0693BDW6b+pa0x6L2uNas/M5Xc81e34hzrcfqYWXRh/TTmIY19nsu3JibH34cld8pWnLlAkksQBsfAtkt9M0UXRLwGZzaQVmqW9I5/LPwlAsIzmnrEJrHPoyTziRaqfNda6RgJ+LuBc/bhGcZfAG1QlHMKKIwI+of2zLKl+KrxCTQMOuVBBv4UEUezBKksdFMp8aAAJagertiRaKPGzdn3i8T9gZHESEUAgGwYA76OsVya0t+0fUXPz0HBo=

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy_production.sh
  on:
    branch: master
